### PR TITLE
Fixes #13: errors with Machine not booting for VMWare Ubuntu 16.04

### LINKED ISSUE #13: VMware boxes built with Fusion 8.5 get stuck on 'Waiting for machine to boot' step
```
$ vagrant up ubuntu1604 --provider=vmware_fusion
Bringing machine 'ubuntu1604' up with 'vmware_fusion' provider...
==> ubuntu1604: Cloning VMware VM: 'file://~/Downloads/vmware-ubuntu1604.box'. This can take some time...
==> ubuntu1604: Verifying vmnet devices are healthy...
==> ubuntu1604: Preparing network adapters...
==> ubuntu1604: Starting the VMware VM...
==> ubuntu1604: Waiting for machine to boot. This may take a few minutes...
```

Tested with Vagrant 1.8.6 and packer 0.10.2. Going to update Packer and see if that helps...

### PR DESCRIPTION
**Pull request by zaiddabaeen**

### CODE REVIEW

**Comment by geerlingguy** [comment]
Will review, thanks!

**Comment by geerlingguy** [comment]
Ah, I was wondering why the fix wasn't working... then realized I didn't apply this branch :P

**Comment by geerlingguy** [comment]
This got it further, but I'm now getting:

```
==> vmware: Configuring network adapters within the VM...
No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug.
```

**Comment by geerlingguy** [comment]
After a `halt` and `up` cycle, back to the old...

```
==> vmware: Setting hostname...
==> vmware: Configuring network adapters within the VM...
No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug.
 12:12:00 ~/Sites/packer/ubuntu1604 $ vagrant halt
==> virtualbox: VM not created. Moving on...
==> virtualbox: [vagrant-hostsupdater] Removing hosts
==> virtualbox: [vagrant-hostsupdater] No machine id, nothing removed from /etc/hosts
v==> vmware: Attempting graceful shutdown of VM...
agrant up==> vmware: [vagrant-hostsupdater] Removing hosts
 13:07:02 ~/Sites/packer/ubuntu1604 $ vagrant up
Bringing machine 'vmware' up with 'vmware_fusion' provider...
Bringing machine 'virtualbox' up with 'vmware_fusion' provider...
==> vmware: Verifying vmnet devices are healthy...
==> vmware: Preparing network adapters...
==> vmware: Starting the VMware VM...
==> vmware: Waiting for machine to boot. This may take a few minutes...
```

**Comment by geerlingguy** [comment]
Somewhat related? https://github.com/mitchellh/vagrant/issues/7070

**Comment by zaiddabaeen** [comment]
That's weird. I have this fix up and running over for the development team right now. I don't think issue 7070 is related. I wouldn't also like to waste time on this, virtualbox does a great job even though it is slower for file syncing.

**Comment by geerlingguy** [comment]
@zaiddabaeen - I typically either use NFS or rsync, so the performance is close to identical (in terms of file access) on VirtualBox. If using native shared folders, then it's a pretty vast difference (in VMware's favor)—but I can't support a box that doesn't offer NFS support out of the box, and that seems to be one of the main difficulties for VMware and the Vagrant plugin right now :/

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/packer-ubuntu-1604/issues/42

**Pull request closed without merging**
